"""empty message

Revision ID: 26deda761088
Revises: 8bedf1c9e84c
Create Date: 2018-05-03 09:18:35.161745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26deda761088'
down_revision = '8bedf1c9e84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    op.add_column('users', sa.Column('celular', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cidade', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dataNascimento', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('objetivo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profissao', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sexo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sexo')
    op.drop_column('users', 'profissao')
    op.drop_column('users', 'objetivo')
    op.drop_column('users', 'dataNascimento')
    op.drop_column('users', 'cidade')
    op.drop_column('users', 'celular')
    op.create_table('pacientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataNascimento', sa.DATETIME(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(), nullable=True),
    sa.Column('cidade', sa.VARCHAR(), nullable=True),
    sa.Column('profissao', sa.VARCHAR(), nullable=True),
    sa.Column('celular', sa.VARCHAR(), nullable=True),
    sa.Column('objetivo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
